# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Jonathan Kingston
author: Jonathan Kingston
subtitle: Development blog
description: > # this means to ignore newlines until "baseurl:"
  Notes from a developer in Nottingham.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://jotter.jonathankingston.co.uk
simple_search: http://google.com/search
twitter_username: kingstonTime
github_username:  jonathanKingston
gems:
  - jekyll-paginate
  - octopress-codeblock
  - jekyll-compass

pages:

permalink: /blog/:year/:month/:day/:title/


# Build settings
markdown: kramdown
